env:
  # Robot
  robot_position: [0, 0]
  robot_radius: 1
  robot_destination: [10, 10]
  # Obstacle
  obstacles_position: [[4, 2], [7, 5], [5, 3]]
  obstacles_radius: [3, 2, 3]
  obstacles_destination: [[1, 4], [3, 10], [5, -1]]
  # Other configs
  delta_t: 1
  v_max: 5
  destination_region: 0.2
