env:
  # Robot
  robot_position: [0, 0]
  robot_radius: 0.5
  robot_destination: [10, 10]
  # Obstacle
  obstacles_position: [[4, 2], [7, 5], [5, 3], [12, 10]]
  obstacles_radius: [2, 2, 2, 1]
  obstacles_destination: [[1, 8], [5, 5], [5, -1], [7, 9]]
  # Other configs
  delta_t: 1
  v_max: 3
  destination_region: 0.2
